### ISSUE TITLE
Question about Velodyne Data

### ISSUE THREAD

**Issue by PatricLee** [navoshta/KITTI-Dataset#1]
Hi, can you help me with a question?
I've been working with Velodyne for a while, and kitti is a very good dataset to me because I don't have to label stuff myself. But the problem is that in my project I use raw points from Velodyne, which only has distance and reflectivity and comes in firing order. Velodyne data from kitti is not stored in firing order, nor is it possible to convert (x, y, z) coordinate back to raw point. Actually the number of points in each file is not even multiple of 64. So could you come up with any idea how I could order the points in firing order? Or at least I could put all 64 points with same rotation together?
Many thanks.

**Comment by alexstaravoitau** [comment]
Sorry @PatricLee, I didn't keep an eye on issues in this repo for a while. As per your question — not sure I can help either I'm afraid, can't think of anything off the top of my head.

**Comment by asimonov-hitachi** [comment]
@PatricLee I think Kitti data skips points where there was no reflection from the object. hence number of points in one Kitti 'velodyne' frame is not divisible by 64. and hence it is not easy to cast the points back into packets corresponding to one vertical scan of 64 points.
