### ISSUE TITLE
Object shape unnatural

### ISSUE THREAD

**Issue by panji530** [navoshta/KITTI-Dataset#11]
Hi,

Thanks for sharing! 

The visualized 3D bbx shape looks unnatural to me. I find that your way of defining local coordinates and converting the yaw angle to its corresponding rotation matrix is different from kitti dev kit:
trackletBox = np.array([
            [-l / 2, -l / 2, l / 2, l / 2, -l / 2, -l / 2, l / 2, l / 2],
            [w / 2, -w / 2, -w / 2, w / 2, w / 2, -w / 2, -w / 2, w / 2],
            [0.0, 0.0, 0.0, 0.0, h, h, h, h]
        ]),
rotMat = np.array([
                [np.cos(yaw), -np.sin(yaw), 0.0],
                [np.sin(yaw), np.cos(yaw), 0.0],
                [0.0, 0.0, 1.0]
            ])

as opposed to the kitti dev kit (Matlab):
% 3D bounding box corners
x_corners = [l/2, l/2, -l/2, -l/2, l/2, l/2, -l/2, -l/2];
y_corners = [0,0,0,0,-h,-h,-h,-h];
z_corners = [w/2, -w/2, -w/2, w/2, w/2, -w/2, -w/2, w/2];

% compute rotational matrix around yaw axis
R = [+cos(object.ry), 0, +sin(object.ry);
                   0, 1,               0;
     -sin(object.ry), 0, +cos(object.ry)];

Could you explain a bit why they are different? 

Thanks

**Comment by qingzi02010** [comment]
+1, exactly same confusion as panji1990

**Comment by alexstaravoitau** [comment]
Apologies @panji1990 and @qingzi02010 — it was too long ago, and I don't remember what was the exact reasoning behind this. Judging by the comments it was supposed to be similar to `computeBox3D` — perhaps it is using a different reference (zero) point  and/or ignores orientation? IIRC, this notebook was supposed to be a quick first version, which I was planning to clean up and improve later (which I never got to, unfortunately).
