### ISSUE TITLE
small issues about the ipython script

### ISSUE THREAD

**Issue by PkuRainBow** [navoshta/KITTI-Dataset#4]
![default](https://user-images.githubusercontent.com/4639578/34726177-3ad7a51c-f58e-11e7-846b-e910837a685b.png)

**Comment by alexstaravoitau** [comment]
Hi @PkuRainBow — I prepared this notebook as a Jupyter Notebook file, I don't think you will be able to run it with CLI ipython. You can launch it with Binder, for instance: 

[![Binder](https://mybinder.org/badge.svg)](https://mybinder.org/v2/gh/navoshta/KITTI-Dataset/master?filepath=kitti-dataset.ipynb)
