### ISSUE TITLE
KITTI Dataset Label Conversion to COCO Dataset format.

### ISSUE THREAD

**Issue by chandanv2** [navoshta/KITTI-Dataset#5]
Hey is there a script available to convert the KITTI Dataset labels into COCO Datset label format?
I have found the script for the other way around. But I am looking for KITTI to COCO conversion.

Thanks!

**Comment by alexstaravoitau** [comment]
Hey @chandanv2 — sorry for a late reply! Not that I'm aware of, no. Although since the issue is closed now I suppose you already found it yourself? 🙂

**Comment by chandanv2** [comment]
@navoshta No I didn't find one. That's okay. Thank you for responding!

**Comment by Samjith888** [comment]
Anyone found script to convert kitti to coco?
