### ISSUE TITLE
A little issue met during the loading tracklets step

### ISSUE THREAD

**Issue by caijicz** [navoshta/KITTI-Dataset#6]
![screenshot from 2018-03-23 16-30-46](https://user-images.githubusercontent.com/36393509/37852077-9e7c6d84-2eb7-11e8-8bc0-f6b2250ba6fe.png)
I followed the step and met this problem. Can you help me find where I am wrong? I think I am wrong at this 'return'. But I tried a lot of method but they didn't work. Thx!
![screenshot from 2018-03-23 16-33-57](https://user-images.githubusercontent.com/36393509/37852171-031e728c-2eb8-11e8-9cf4-12d775c004e7.png)

**Comment by Omar-Aboelsoud** [comment]
Hello ,  I am facing a similar problem , sounds it is not happy with this line
frame_tracklets[absoluteFrameNumber] = frame_tracklets[absoluteFrameNumber] + [cornerPosInVelo]
     51             frame_tracklets_types[absoluteFrameNumber] = frame_tracklets_types[absoluteFrameNumber] + [
     52                 tracklet.objectType]

![image](https://user-images.githubusercontent.com/6435445/38197971-0bb1aa2e-368b-11e8-9ede-1d5ebba93524.png)

**Comment by caijicz** [comment]
I already solved this problem. Actually it is a environment problem. This code is written in python3, but  the pykitti is used in python2. After change the environment to python3, it can run smoothly.

**Comment by Omar-Aboelsoud** [comment]
Hello, 
I am searching for code to label the velodyne points - point by point 

any thoughts , how can i make this ?

**Comment by alexstaravoitau** [comment]
Sorry for a late reply!

@caijicz — great, yes I indeed updated tracklet parsing utilities to Python 3.
@Omar-Aboelsoud — not sure I'll be able to help, but as advised try digging into how `pykitti` handles point clouds, or maybe even consider augmenting existing data (depending on what you're trying to do with it).
