### ISSUE TITLE
Errors in executing the code

### ISSUE THREAD

**Issue by theC0der512** [navoshta/KITTI-Dataset#7]
Hi Alex,
I am trying to execute your code & use some parts of it to improve sensing for self driving cars. I am constantly facing null error in Xml file and there's a syntax error in accessing same localhost file. Please go through the drive link for reference. I am fairly new to this and your clarification might help me for my graduate project.
Awaiting your reply. Thank you for your valuable time.
Kind Regards,
Chinmay Upadhye

[https://drive.google.com/open?id=1I12Ge_SEFK8XSbn760Xp_2UjmlN6ULMc](url)

**Comment by alexstaravoitau** [comment]
Hey — you've modified the file, accidentally removing one dimension in rotation matrix.

```python
rotMat = np.array([
    [np.cos(yaw), -np.sin(yaw), 0.0],
    [np.sin(yaw), np.cos(yaw), 0.0],
    [0.0, 0.0, 1.0]
])
```

**Comment by theC0der512** [comment]
Hi Alex,
Thanks for your input. It was helpful. I just want you to inform you that
there might be an key error in tracklet_labels.xml file. I was having key
error for absoluteFrameNumber = 108. This might not be a problem everybody
faces but I just thought you should know.
Have a nice day !
Kind regards,
Chinmay
