### ISSUE TITLE
Provide a licence

### ISSUE THREAD

**Issue by Kuhno92** [navoshta/KITTI-Dataset#8]
Hello, i really enjoyed reading your article and your repository about the kitti dataset exploration.
Im an computer science student and would really like to use your code for further kitti dataset exploration and machine learning tasks.
Would be great if you could add a licence to your repository so i can refer to it.
;)

**Comment by alexstaravoitau** [comment]
Thanks! I added MIT license (since `pykitti` is also MIT).
